# Numpy CheatSheet

In [1]:
# Importing numpy
import numpy as np

---

In [2]:
# Tạo mảng
arr = np.array([1, 2, 3])  # Mảng 1D
arr_2d = np.array([[1, 2], [3, 4]])  # Mảng 2D
arr_zeros = np.zeros((3, 3))  # Mảng chứa toàn số 0
arr_ones = np.ones((2, 4))  # Mảng chứa toàn số 1
arr_range = np.arange(0, 10, 2)  # Mảng với phạm vi
arr_linspace = np.linspace(0, 10, 5)  # Mảng với các giá trị được phân bổ đều

In [12]:
# In kết quả các mảng
print("arr:\n", arr)
print("arr_2d:\n", arr_2d)
print("arr_zeros:\n", arr_zeros)
print("arr_ones:\n", arr_ones)
print("arr_range:\n", arr_range)
print("arr_linspace:\n", arr_linspace)

arr:
 [1 2 3]
arr_2d:
 [[1 2]
 [3 4]]
arr_zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
arr_ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arr_range:
 [0 2 4 6 8]
arr_linspace:
 [ 0.   2.5  5.   7.5 10. ]


---

In [8]:
# Thuộc tính của mảng
arr_shape = arr_2d.shape  # Kích thước của mảng
arr_size = arr_2d.size  # Tổng số phần tử
arr_dtype = arr_2d.dtype  # Kiểu dữ liệu của phần tử
arr_itemsize = arr_2d.itemsize  # Kích thước bộ nhớ của một phần tử
arr_ndim = arr_2d.ndim  # Số chiều của mảng

In [9]:
# In kết quả các thuộc tính
print("Shape của arr_2d:", arr_shape)
print("Kích thước của arr_2d:", arr_size)
print("Kiểu dữ liệu của arr_2d:", arr_dtype)
print("Kích thước bộ nhớ của một phần tử trong arr_2d:", arr_itemsize)
print("Số chiều của arr_2d:", arr_ndim)

Shape của arr_2d: (2, 2)
Kích thước của arr_2d: 4
Kiểu dữ liệu của arr_2d: int32
Kích thước bộ nhớ của một phần tử trong arr_2d: 4
Số chiều của arr_2d: 2


---

In [10]:
# Chỉ mục và cắt mảng
arr_slice = arr_2d[1, :]  # Cắt một dòng
arr_subarray = arr_2d[:2, :2]  # Cắt mảng con
arr_reverse = arr[::-1]  # Đảo ngược mảng
arr_indexing = arr_2d[1][1]  # Truy cập phần tử cụ thể

In [13]:
# In kết quả cắt mảng
print("arr_slice:", arr_slice)
print("arr_subarray: \n", arr_subarray)
print("arr_reverse:", arr_reverse)
print("arr_indexing:", arr_indexing)

arr_slice: [3 4]
arr_subarray: 
 [[1 2]
 [3 4]]
arr_reverse: [3 2 1]
arr_indexing: 4


---

In [15]:
# Các phép toán toán học
arr_add = arr + 2  # Cộng 2 vào từng phần tử
arr_mul = arr * 2  # Nhân từng phần tử với 2
arr_dot = np.dot(arr_2d, np.array([1, 2]))  # Phép nhân ma trận chỉ xảy ra với ma trận có dạng a*b và b*c (trong trường hợp này là 2*2 và 2*1)
arr_sum = arr_2d.sum()  # Tổng tất cả phần tử
arr_mean = arr_2d.mean()  # Trung bình cộng tất cả phần tử
arr_std = arr_2d.std()  # Độ lệch chuẩn
arr_max = arr_2d.max()  # Phần tử lớn nhất
arr_min = arr_2d.min()  # Phần tử nhỏ nhất

In [16]:
# In kết quả phép toán toán học
print("arr_add:", arr_add)
print("arr_mul:", arr_mul)
print("arr_dot:", arr_dot)
print("arr_sum:", arr_sum)
print("arr_mean:", arr_mean)
print("arr_std:", arr_std)
print("arr_max:", arr_max)
print("arr_min:", arr_min)

arr_add: [3 4 5]
arr_mul: [2 4 6]
arr_dot: [ 5 11]
arr_sum: 10
arr_mean: 2.5
arr_std: 1.118033988749895
arr_max: 4
arr_min: 1


---

In [17]:
# Thay đổi hình dạng mảng
arr_reshaped = arr_2d.reshape((4, 1))  # Thay đổi hình dạng mảng
arr_flat = arr_2d.flatten()  # Làm phẳng mảng 2D

In [19]:
# In kết quả thay đổi hình dạng
print("arr_reshaped: \n", arr_reshaped)
print("arr_flat:", arr_flat)

arr_reshaped: 
 [[1]
 [2]
 [3]
 [4]]
arr_flat: [1 2 3 4]


---

In [20]:
# Đại số tuyến tính
arr_inv = np.linalg.inv(arr_2d)  # Ma trận nghịch đảo
arr_transpose = arr_2d.T  # Chuyển vị của ma trận
arr_eig = np.linalg.eig(arr_2d)  # Tính trị riêng và vector riêng

In [22]:
# In kết quả đại số tuyến tính
print("arr_inv: \n", arr_inv)
print("arr_transpose: \n", arr_transpose)
print("arr_eig: \n", arr_eig)

arr_inv: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
arr_transpose: 
 [[1 3]
 [2 4]]
arr_eig: 
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


---

In [23]:
# Số ngẫu nhiên
arr_random = np.random.rand(3, 3)  # Số ngẫu nhiên trong phạm vi [0, 1)
arr_random_int = np.random.randint(1, 10, (3, 3))  # Số nguyên ngẫu nhiên từ 1 đến 10
arr_normal = np.random.randn(3, 3)  # Phân phối chuẩn
arr_uniform = np.random.uniform(0, 1, (3, 3))  # Phân phối đều trong phạm vi [0, 1)
arr_choice = np.random.choice([1, 2, 3, 4], size=(3, 3))  # Chọn ngẫu nhiên từ các giá trị [1, 2, 3, 4]
arr_shuffle = np.random.shuffle(arr_2d)  # Xáo trộn các phần tử của mảng
np.random.seed(42)  # Đặt hạt giống cho số ngẫu nhiên để đảm bảo kết quả lặp lại

In [25]:
# In kết quả số ngẫu nhiên
print("arr_random: \n", arr_random)
print("arr_random_int: \n", arr_random_int)
print("arr_normal: \n", arr_normal)
print("arr_uniform: \n", arr_uniform)
print("arr_choice: \n", arr_choice)

arr_random: 
 [[0.82076934 0.45931757 0.06564014]
 [0.16436413 0.93848956 0.70997099]
 [0.88136639 0.40873042 0.96383939]]
arr_random_int: 
 [[3 8 2]
 [2 6 4]
 [5 2 7]]
arr_normal: 
 [[ 1.0340927  -1.35033242 -0.11594918]
 [ 1.54332189  1.12734177 -1.18442198]
 [ 1.02664854  0.58823096  0.9661148 ]]
arr_uniform: 
 [[0.71490727 0.39672181 0.28140939]
 [0.38008926 0.22097021 0.05038188]
 [0.20989373 0.59870238 0.32593697]]
arr_choice: 
 [[1 4 1]
 [2 2 1]
 [1 2 2]]


---

In [ ]:
arr_2d = np.array([[1, 2], [3, 4]])  # Ma trận 2x2
arr = np.array([1, 2])  # Mảng 1D có kích thước (2,)

# Phép toán Broadcasting - Thực hiện phép toán với 2 mảng có kích thước khác nhau
arr_broadcast = arr_2d + arr  # Phép toán Broadcasting

In [ ]:
# In kết quả phép toán Broadcasting
print("arr_broadcast: \n", arr_broadcast)

arr_broadcast: 
 [[2 4]
 [4 6]]


---

In [30]:
# Phép toán Boolean
arr_bool = arr_2d > 2  # So sánh các phần tử
arr_all = np.all(arr_2d > 2)  # Kiểm tra xem tất cả phần tử có lớn hơn 2 không
arr_any = np.any(arr_2d > 2)  # Kiểm tra xem có phần tử nào lớn hơn 2 không

In [32]:
# In kết quả phép toán Boolean
print("arr_bool: \n", arr_bool)
print("arr_all:", arr_all)
print("arr_any:", arr_any)

arr_bool: 
 [[False False]
 [ True  True]]
arr_all: False
arr_any: True


---

In [33]:
# Nối và chia mảng
arr_vstack = np.vstack([arr_2d, arr_2d])  # Nối mảng theo chiều dọc
arr_hstack = np.hstack([arr_2d, arr_2d])  # Nối mảng theo chiều ngang
arr_split = np.split(arr_2d, 2, axis=0)  # Chia mảng thành 2 phần theo chiều dọc

In [35]:
# In kết quả nối và chia mảng
print("arr_vstack: \n", arr_vstack)
print("arr_hstack: \n", arr_hstack)
print("arr_split: \n", arr_split)

arr_vstack: 
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]
arr_hstack: 
 [[1 2 1 2]
 [3 4 3 4]]
arr_split: 
 [array([[1, 2]]), array([[3, 4]])]


---

In [36]:
# Lưu và tải mảng
np.save('array.npy', arr_2d)  # Lưu mảng vào file
loaded_arr = np.load('array.npy')  # Tải mảng từ file

In [38]:
# In kết quả tải mảng
print("loaded_arr: \n", loaded_arr)

loaded_arr: 
 [[1 2]
 [3 4]]
